module.exports = {
    accounts: [
        ['1', 'ACTIVO', 'activo'],
        ['11', 'Activo Corriente', 'activo'],
        ['111', 'Efectivo y Equivalentes de Efectivo', 'activo'],
        ['1111', 'Caja', 'activo'],
        ['1112', 'Caja Chica', 'activo'],
        ['1113', 'Bancos Cuenta Cheques', 'activo'],
        ['1114', 'Depósitos a Plazo', 'activo'],
        ['1115', 'Valores Negociables o Bonos', 'activo'],
        ['112', 'Inversiones  ', 'activo'],
        ['1121', 'Inversiones en Bonos', 'activo'],
        ['1122', 'Depósitos a Plazo', 'activo'],
        ['113', 'Deudores comerciales y otras Cuentas por Cobrar', 'activo'],
        ['1131', 'Clientes ', 'activo'],
        ['1132', 'Documentos por Cobrar ', 'activo'],
        ['1133', 'Deudores Varios', 'activo'],
        ['1134', 'Intereses por Cobrar', 'activo'],
        ['1135', 'Impuestos Diferidos por Cobrar', 'activo'],
        ['1136', 'Rentas por Cobrar', 'activo'],
        ['1137', 'Impuestos por Cobrar', 'activo'],
        ['1138', 'Funcionarios y Empleados o Anticipo a Empleados', 'activo'],
        ['114', 'Inventarios ', 'activo'],
        ['1141', 'Inventario de Mercaderia (almacén)', 'activo'],
        ['1142', 'Inventario de Materia Prima', 'activo'],
        ['1143', 'Inventario de Productos en Proceso', 'activo'],
        ['1144', 'Inventario de Productos Terminados', 'activo'],
        ['115', 'Pagos por Anticipados ', 'activo'],
        ['1151', 'Papelería y Útiles', 'activo'],
        ['1152', 'Material de Empaque', 'activo'],
        ['1153', 'Material de Aseo', 'activo'],
        ['1154', 'Propaganda y Publicidad', 'activo'],
        ['1155', 'Anticipos a Proveedores', 'activo'],
        ['1156', 'Rentas Pagadas por Anticipado', 'activo'],
        ['1157', 'Suscripciones Pagadas por Anticipado', 'activo'],
        ['1158', 'Intereses Pagados por Anticipado', 'activo'],
        ['1159', 'Impuestos Pagados por Anticipado', 'activo'],
        ['11510', 'Accesorios y Suministros', 'activo'],
        ['11511', 'Primas de Seguros', 'activo'],
        ['12', 'Activo No Corriente', 'activo'],
        ['121', 'Inversiones y Valores', 'activo'],
        ['1211', 'Depositos a Plazo fijo', 'activo'],
        ['1212', 'Inversiones en Acciones', 'activo'],
        ['1213', 'Inversiones a Bonos', 'activo'],
        ['1214', 'Inversiones en Negocios Conjuntos', 'activo'],
        ['1215', 'Depósitos a Plazo', 'activo'],
        ['122', 'Propiedad, Planta y Equipo', 'activo'],
        ['1221', 'Terrenos ', 'activo'],
        ['1222', 'Edificios', 'activo'],
        ['1223', 'Maquinaria', 'activo'],
        ['1224', 'Mobiliaria y Equipo', 'activo'],
        ['1225', 'Vehículos', 'activo'],
        ['1226', 'Equipo de Transporte', 'activo'],
        ['1227', 'Equipo de Reparto', 'activo'],
        ['1228', 'Herramientas', 'activo'],
        ['123', 'Propiedades de Inversión ( disponibles para alquiler o venta)', 'activo'],
        ['1231', 'Terrenos ', 'activo'],
        ['1232', 'Edificios', 'activo'],
        ['124', 'Activos Intangibles', 'activo'],
        ['1241', 'Plusvalía ( Crédito Mercantil)', 'activo'],
        ['1242', 'Derechos de Autor', 'activo'],
        ['1243', 'Marcas y Patentes', 'activo'],
        ['1244', 'Licencias', 'activo'],
        ['1245', 'Programas Informáticos', 'activo'],
        ['125', 'Otros Activos', 'activo'],
        ['1251', 'Bancos (Cuenta congelada)', 'activo'],
        ['1252', 'Documentos por Cobrar (a largo plazo)', 'activo'],
        ['1253', 'Depósitos en Garantía', 'activo'],
        ['2', 'Pasivo', 'pasivo'],
        ['21', 'Pasivo Corriente', 'pasivo'],
        ['211', 'Cuentas y Documentos por Pagar', 'pasivo'],
        ['2111', 'Proveedores (cuentas por pagar)', 'pasivo'],
        ['2112', 'Sueldos y Salios por Pagar', 'pasivo'],
        ['2113', 'Impuestos por Pagar', 'pasivo'],
        ['2114', 'Intereses por Pagar', 'pasivo'],
        ['2115', 'Acreedores Varios', 'pasivo'],
        ['2116', 'Documentos por Pagar', 'pasivo'],
        ['2117', 'Hipotecas por Pagar', 'pasivo'],
        ['212', 'Préstamos', 'pasivo'],
        ['2121', 'Préstamos Bancarios', 'pasivo'],
        ['2122', 'Préstamos Hipotecarios', 'pasivo'],
        ['213', 'Obligaciones por Provisiones', 'pasivo'],
        ['2131', 'Provisiones para Compensaciones a Empleados', 'pasivo'],
        ['2132', 'Provisiones para Cubrir Garantías a Clientes', 'pasivo'],
        ['2133', 'Provisiones para Cubrir Reclamos Legales', 'pasivo'],
        ['214', 'Cobros Anticipados', 'pasivo'],
        ['2141', 'Rentas Cobradas por Anticipado', 'pasivo'],
        ['2142', 'Intereses Cobrados por Anticipado', 'pasivo'],
        ['2143', 'Servicios Cobrados por Anticipado', 'pasivo'],
        ['2144', 'Anticipos a Clientes', 'pasivo'],
        ['22', 'Pasivo No Corriente', 'pasivo'],
        ['221', 'Cuentas y Documentos por Pagar', 'pasivo'],
        ['2211', 'Acreedores Varios', 'pasivo'],
        ['2212', 'Documentos por Pagar', 'pasivo'],
        ['2213', 'Obligaciones por Provisiones', 'pasivo'],
        ['222', 'Prestamos', 'pasivo'],
        ['2221', 'Prestamos Bancarios', 'pasivo'],
        ['2222', 'Hipotecas por Pagar', 'pasivo'],
        ['223', 'Provisiones ', 'pasivo'],
        ['2231', 'Provisiones para Compensaciones a Empleados', 'pasivo'],
        ['2232', 'Provisiones para Cubrir Garantías a Clientes', 'pasivo'],
        ['2233', 'Provisiones para Cubrir Reclamos Legales', 'pasivo'],
        ['224', 'Cobros Anticipados', 'pasivo'],
        ['2241', 'Rentas Cobradas por Anticipado', 'pasivo'],
        ['2242', 'Interses Cobrados por Anticipado', 'pasivo'],
        ['2243', 'Servicios Cobrados por Anticipado', 'pasivo'],
        ['3', 'Patrimonio ', 'patrimonio'],
        ['31', 'Comerciante Individual', 'patrimonio'],
        ['311', 'Capital', 'patrimonio'],
        ['312', 'Resultados Acumulados', 'patrimonio'],
        ['3121', 'Utilidades o perdidas de años anteriores', 'patrimonio'],
        ['3122', 'Utilidad o Perdida Neta del Período', 'patrimonio'],
        ['3123', 'Perdidas no Aplicadas', 'patrimonio'],
        ['32', 'Empresa Jurídica', 'patrimonio'],
        ['321', 'Capital Social', 'patrimonio'],
        ['322', 'Reservas', 'patrimonio'],
        ['3221', 'Reserva Legal', 'patrimonio'],
        ['3222', 'Reservas de Prevision', 'patrimonio'],
        ['3223', 'Reserva de Reinversion', 'patrimonio'],
        ['3224', 'Reserva de Educacion', 'patrimonio'],
        ['323', 'Resultados Acumulados', 'patrimonio'],
        ['3231', 'Utilidad o Pérdida de Años Anteriores', 'patrimonio'],
        ['3232', 'Utilidad o Pérdida Neta del Ejercicio', 'patrimonio'],
        ["4001", " Ventas", "Cuentas de Ingresos"],
        [
            "4002",
            "Productos Financieros", "Cuentas de Ingresos"
        ],
        [
            "4003",
            "Otros Productos","Cuentas de Ingresos"
        ],
        [
            "4004",
            "Rebajas Sobre Compras","Cuentas de Ingresos"
        ],
        [
            "4005",
            "Devoluciones Sobre Compras","Cuentas de Ingresos"
        ],
        [
            "4006",
            "Descuento Sobre Compras","Cuentas de Ingresos"
        ],
        [
            "4007",
            "Ingresos por Servicios","Cuentas de Ingresos"
        ],
        [
            "5",
            "Cuentas de Costos y Gastos", "Cuentas de Costos y Gastos"
        ],
        [
            "5001",
            "Devoluciones Sobre Ventas", "Cuentas de Costos y Gastos"
        ],
        [
            "5002",
            "Rebajas Sobre Ventas", "Cuentas de Costos y Gastos"
        ],
        [
            "5003",
            "Descuentos Sobre Ventas", "Cuentas de Costos y Gastos"
        ],
        [
            "5004",
            "Compras Brutas", "Cuentas de Costos y Gastos"
        ],
        [
            "5005",
            "Gastos Sobre Compras", "Cuentas de Costos y Gastos"
        ],
        [
            "5006",
            "Gastos de Administración", "Cuentas de Costos y Gastos"
        ],
        [
            "5007",
            "Gastos Financieros", "Cuentas de Costos y Gastos"
        ],
        [
            "5008",
            "Gastos de Venta", "Cuentas de Costos y Gastos"
        ],
        [
            "6000",
            "Impuesto Sobre Venta", "Cuentas de Costos y Gastos"
        ]
    ]
}//